Repository Knock-and-knock/backend, pull requests merged in 2024-08, with the labels that each got.

#5 [Deploy] Github action을 위한 workflow 제작
  .dockerignore
  .github/workflows/main.yml
  Dockerfile
  build.gradle
  src/main/java/com/shinhan/knockknock/domain/entity/TestEntity.java
Labels: 🌏deploy

#7 [Refactor] workflow 수정
  .github/workflows/main.yml
Labels: 🌏deploy, 🔄️refactoring

#9 🌟(#4) Swagger 테스트
  .gitignore
  build.gradle
  src/main/java/com/shinhan/knockknock/controller/SwaggerTestController.java
  src/main/java/com/shinhan/knockknock/swagger/SwaggerConfig.java
Labels: 🌟feature

#14 Feat welfare table
  gradle/wrapper/gradle-wrapper.properties
Labels: ⚙setting

#15 [Feat] Card Entity 생성
  src/main/java/com/shinhan/knockknock/domain/entity/CardCategoryEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/CardEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/CardHistoryEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/CardIssueEntity.java
  src/main/resources/application.properties
Labels: 🌟feature

#17 [Feat] User domain 생성
  src/main/java/com/shinhan/knockknock/config/EnvConfig.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/entity/UserEntity.java
Labels: 🌟feature

#23 [Feat] 카드 조회 및 기능 수정
  src/main/java/com/shinhan/knockknock/controller/CardIssueRestController.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateCardIssueResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/ReadCardResponse.java
  src/main/java/com/shinhan/knockknock/service/CardIssueService.java
  src/main/java/com/shinhan/knockknock/service/CardIssueServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/CardService.java
  src/main/java/com/shinhan/knockknock/service/CardServiceImpl.java
  src/main/resources/application.properties
Labels: 🌟feature

#26 🌟(#11 ) 복지, 복지예약
  src/main/java/com/shinhan/knockknock/controller/WelfareController.java
  src/main/java/com/shinhan/knockknock/domain/dto/WelfareBookRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/WelfareBookResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/WelfareRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/WelfareResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/WelfareBookEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/WelfareEntity.java
  src/main/java/com/shinhan/knockknock/repository/WelfareBookRepository.java
  src/main/java/com/shinhan/knockknock/repository/WelfareRepository.java
  src/main/java/com/shinhan/knockknock/service/WelfareBookService.java
  src/main/java/com/shinhan/knockknock/service/WelfareBookServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/WelfareService.java
  src/main/java/com/shinhan/knockknock/service/WelfareServiceImpl.java
Labels: 🌟feature

#31 🌟(#11 ) 복지, 복지예약 restcontroller
  src/main/java/com/shinhan/knockknock/controller/WelfareController.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateWelfareBookRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateWelfareRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/ReadWelfareBookResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/ReadWelfareResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/WelfareBookEntity.java
  src/main/java/com/shinhan/knockknock/restcontroller/WelfareBookRestController.java
  src/main/java/com/shinhan/knockknock/restcontroller/WelfareRestController.java
  src/main/java/com/shinhan/knockknock/service/WelfareBookService.java
  src/main/java/com/shinhan/knockknock/service/WelfareBookServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/WelfareService.java
  src/main/java/com/shinhan/knockknock/service/WelfareServiceImpl.java
Labels: 🌟feature

#28 🌟(#27 ) 카드 발급 비동기 처리
  src/main/java/com/shinhan/knockknock/config/AsyncConfig.java
  src/main/java/com/shinhan/knockknock/controller/CardIssueRestController.java
  src/main/java/com/shinhan/knockknock/domain/entity/CardEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/CardIssueEntity.java
  src/main/java/com/shinhan/knockknock/service/CardIssueServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/CardService.java
  src/main/java/com/shinhan/knockknock/service/CardServiceImpl.java
Labels: 🌟feature

#39 🌟(#21) 대화방 Entity 및 CRUD 구현
  src/main/java/com/shinhan/knockknock/controller/ConversationRoomController.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversationroom/ConversationRoomCreateResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversationroom/ConversationRoomResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversationroom/ConversationRoomUpdateRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversationroom/MessageResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/ConversationLogEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/ConversationRoomEntity.java
  src/main/java/com/shinhan/knockknock/repository/ConversationLogRepository.java
  src/main/java/com/shinhan/knockknock/repository/ConversationRoomRepository.java
  src/main/java/com/shinhan/knockknock/service/ConversationRoomService.java
  src/main/java/com/shinhan/knockknock/service/ConversationRoomServiceImpl.java
Labels: 🌟feature

#41 🌟(#34) 가족카드 기능 추가 및 수정
  src/main/java/com/shinhan/knockknock/controller/CardController.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateCardIssueRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/ReadCardResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/CardEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/CardIssueEntity.java
  src/main/java/com/shinhan/knockknock/repository/CardRepository.java
  src/main/java/com/shinhan/knockknock/service/CardIssueService.java
  src/main/java/com/shinhan/knockknock/service/CardIssueServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/CardService.java
  src/main/java/com/shinhan/knockknock/service/CardServiceImpl.java
Labels: 🌟feature

#37 🌟(#30 ) 복지, 복지 예약 crud 테스트
  src/main/java/com/shinhan/knockknock/controller/WelfareBookController.java
  src/main/java/com/shinhan/knockknock/controller/WelfareController.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateWelfareBookRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/ReadWelfareBookResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/WelfareBookEntity.java
  src/main/java/com/shinhan/knockknock/restcontroller/WelfareRestController.java
  src/main/java/com/shinhan/knockknock/service/WelfareBookService.java
  src/main/java/com/shinhan/knockknock/service/WelfareBookServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/WelfareServiceImpl.java
  src/test/java/com/shinhan/knockknock/domain/entity/WelfareEntityTest.java
  src/test/java/com/shinhan/knockknock/service/WelfareBookServiceTest.java
  src/test/java/com/shinhan/knockknock/service/WelfareServiceTest.java
Labels: 💯test

#33 🌟(#18 ) 회원가입 구현
  build.gradle
  src/main/java/com/shinhan/knockknock/config/SecurityConfig.java
  src/main/java/com/shinhan/knockknock/controller/UserController.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/UserValidationResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/UserEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/UserRole.java
  src/main/java/com/shinhan/knockknock/repository/UserRepository.java
  src/main/java/com/shinhan/knockknock/service/UserService.java
  src/main/java/com/shinhan/knockknock/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/shinhan/knockknock/UserControllerTest.java
Labels: 🌟feature

#45 🌟(#40 ) Conversation Log CRUD 추가
  src/main/java/com/shinhan/knockknock/controller/ConversationLogController.java
  src/main/java/com/shinhan/knockknock/controller/ConversationRoomController.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversationroom/ConversationLogRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversationroom/ConversationLogResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/ConversationLogEntity.java
  src/main/java/com/shinhan/knockknock/service/ConversationLogService.java
  src/main/java/com/shinhan/knockknock/service/ConversationLogServiceImpl.java
Labels: 🌟feature

#51 🌟(#42 ) 카드 발급 테스트 코드 작성
  build.gradle
  src/main/java/com/shinhan/knockknock/controller/CardController.java
  src/main/java/com/shinhan/knockknock/service/CardServiceImpl.java
  src/test/java/com/shinhan/knockknock/controller/CardControllerTest.java
  src/test/java/com/shinhan/knockknock/repository/CardIssueRepositoryTest.java
  src/test/java/com/shinhan/knockknock/repository/CardRepositoryTest.java
  src/test/java/com/shinhan/knockknock/service/CardIssueServiceImplTest.java
  src/test/java/com/shinhan/knockknock/service/CardServiceImplTest.java
Labels: 💯test

#57 🌟(#47 ) 매칭 기능 구현
  src/main/java/com/shinhan/knockknock/controller/CardController.java
  src/main/java/com/shinhan/knockknock/controller/ConversationRoomController.java
  src/main/java/com/shinhan/knockknock/controller/MatchController.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateMatchRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateMatchResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/DeleteMatchResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/UpdateMatchRequest.java
  src/main/java/com/shinhan/knockknock/domain/entity/MatchEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/UserEntity.java
  src/main/java/com/shinhan/knockknock/repository/MatchRepository.java
  src/main/java/com/shinhan/knockknock/repository/UserRepository.java
  src/main/java/com/shinhan/knockknock/service/MatchService.java
  src/main/java/com/shinhan/knockknock/service/MatchServiceImpl.java
Labels: 🌟feature

#61 🌟(#52 ) 카드 내역 repo, service, controller 생성
  src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateCardCategoryRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateCardHistoryRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/ReadCardCategoryResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/ReadCardHistoryResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/CardHistoryEntity.java
  src/main/java/com/shinhan/knockknock/repository/CardCategoryRepository.java
  src/main/java/com/shinhan/knockknock/repository/CardHistoryRepository.java
  src/main/java/com/shinhan/knockknock/service/CardCategoryService.java
  src/main/java/com/shinhan/knockknock/service/CardCategoryServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/CardHistoryService.java
  src/main/java/com/shinhan/knockknock/service/CardHistoryServiceImpl.java
  src/main/resources/application.properties
Labels: 🌟feature

#64 🌟(#49 ) Swagger config 수정 및 test db setting 추가
  src/main/java/com/shinhan/knockknock/config/SecurityConfig.java
  src/main/java/com/shinhan/knockknock/config/SwaggerConfig.java
  src/main/resources/application.properties
  src/test/java/com/shinhan/knockknock/service/WelfareServiceTest.java
  src/test/resources/application-test.properties
Labels: ⚙setting, 🌟feature

#67 🌟(#3 ) workflow 수정
  .github/workflows/main.yml
Labels: 🌏deploy

#69 🌟(#3 ) Dockerfile 수정
  Dockerfile
Labels: 🌏deploy

#71 🌟(#3 ) Dockerfile 업데이트
  Dockerfile
Labels: 🌏deploy

#73 🌟(#3 ) EnvConfig 수정
  Dockerfile
  src/main/java/com/shinhan/knockknock/config/EnvConfig.java
Labels: 🌏deploy

#65 🌟(#49 ) 대화 관련 테스트 코드 추가
  src/test/java/com/shinhan/knockknock/service/ConversationLogTest.java
  src/test/java/com/shinhan/knockknock/service/ConversationRoomTest.java
Labels: 💯test

#66 🌟(#59 ) 회원가입 및 로그인 테스트
  src/main/java/com/shinhan/knockknock/controller/AuthController.java
  src/main/java/com/shinhan/knockknock/controller/MatchController.java
  src/main/java/com/shinhan/knockknock/controller/UserController.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/LoginUserResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/TokenResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/UserEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/UserRoleEnum.java
  src/main/java/com/shinhan/knockknock/service/AuthService.java
  src/main/java/com/shinhan/knockknock/service/CustomUserDetailsService.java
  src/test/java/com/shinhan/knockknock/UserControllerTest.java
  src/test/java/com/shinhan/knockknock/controller/AuthControllerTest.java
  src/test/java/com/shinhan/knockknock/controller/UserControllerTest.java
  src/test/java/com/shinhan/knockknock/service/UserServiceTest.java
Labels: 💯test

#89 🌟(#63) 스웨거 수정 및 알림 Entity
  src/main/java/com/shinhan/knockknock/controller/CardController.java
  src/main/java/com/shinhan/knockknock/domain/entity/NotificationEntity.java
Labels: 🌟feature

#90 🌟(#83 ) 간편 로그인 구현
  src/main/java/com/shinhan/knockknock/controller/AuthController.java
  src/main/java/com/shinhan/knockknock/domain/dto/IdLoginUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/LoginUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/SimpleLoginUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/entity/LoginTypeEnum.java
  src/main/java/com/shinhan/knockknock/service/AuthService.java
Labels: 🌟feature

#91 🌟(#81 ) 코드Repactoring
  src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
  src/main/java/com/shinhan/knockknock/controller/WelfareBookController.java
  src/main/java/com/shinhan/knockknock/controller/WelfareController.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateCardCategoryRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateCardHistoryRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateWelfareBookRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateWelfareRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/LoginUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/ReadCardCategoryResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/ReadCardHistoryResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/ReadWelfareBookResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/ReadWelfareResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/CardHistoryEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/UserEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/WelfareBookEntity.java
  src/main/java/com/shinhan/knockknock/repository/CardHistoryRepository.java
  src/main/java/com/shinhan/knockknock/repository/UserRepository.java
  src/main/java/com/shinhan/knockknock/service/CardCategoryService.java
  src/main/java/com/shinhan/knockknock/service/CardCategoryServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/CardHistoryService.java
  src/main/java/com/shinhan/knockknock/service/CardHistoryServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/WelfareBookService.java
  src/main/java/com/shinhan/knockknock/service/WelfareBookServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/WelfareService.java
  src/main/java/com/shinhan/knockknock/service/WelfareServiceImpl.java
Labels: 🔄️refactoring

#92 🌟(#91) LoginType 중복제거
  src/main/java/com/shinhan/knockknock/domain/dto/LoginUserRequest.java
Labels: 🐞bugfix

#93 🌟(#91 ) 테스트 코드 수정
  src/main/java/com/shinhan/knockknock/domain/dto/IdLoginUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/SimpleLoginUserRequest.java
  src/test/java/com/shinhan/knockknock/controller/AuthControllerTest.java
  src/test/java/com/shinhan/knockknock/service/WelfareBookServiceTest.java
  src/test/java/com/shinhan/knockknock/service/WelfareServiceTest.java
Labels: 🔄️refactoring, 💯test

#99 🌟(#63 ) 알림 서비스 구현 및 테스트 코드 수정
  src/main/java/com/shinhan/knockknock/config/SecurityConfig.java
  src/main/java/com/shinhan/knockknock/controller/NotificationController.java
  src/main/java/com/shinhan/knockknock/repository/EmitterRepository.java
  src/main/java/com/shinhan/knockknock/service/NotificationService.java
  src/main/java/com/shinhan/knockknock/service/NotificationServiceImpl.java
  src/main/resources/static/Notification.html
  src/test/java/com/shinhan/knockknock/controller/CardControllerTest.java
  src/test/java/com/shinhan/knockknock/service/CardServiceImplTest.java
Labels: 🌟feature

#100 🌟(#93 ) 조회방식 수정 및 test코드 수정
  src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
  src/main/java/com/shinhan/knockknock/controller/WelfareBookController.java
  src/main/java/com/shinhan/knockknock/controller/WelfareController.java
  src/main/java/com/shinhan/knockknock/domain/dto/cardcategory/CreateCardCategoryRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/cardcategory/ReadCardCategoryResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/cardhistory/CreateCardHistoryRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/cardhistory/ReadCardHistoryResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/welfare/CreateWelfareRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/welfare/ReadWelfareResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/welfarebook/CreateWelfareBookRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/welfarebook/ReadWelfareBookResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/CardHistoryEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/WelfareBookEntity.java
  src/main/java/com/shinhan/knockknock/repository/UserRepository.java
  src/main/java/com/shinhan/knockknock/repository/WelfareBookRepository.java
  src/main/java/com/shinhan/knockknock/repository/WelfareRepository.java
  src/main/java/com/shinhan/knockknock/service/CardCategoryService.java
  src/main/java/com/shinhan/knockknock/service/CardCategoryServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/CardHistoryService.java
  src/main/java/com/shinhan/knockknock/service/CardHistoryServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/MatchServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/WelfareBookService.java
  src/main/java/com/shinhan/knockknock/service/WelfareBookServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/WelfareService.java
  src/main/java/com/shinhan/knockknock/service/WelfareServiceImpl.java
  src/test/java/com/shinhan/knockknock/controller/CardHistoryControllerTest.java
  src/test/java/com/shinhan/knockknock/service/ConversationLogTest.java
  src/test/java/com/shinhan/knockknock/service/WelfareBookServiceTest.java
  src/test/java/com/shinhan/knockknock/service/WelfareServiceTest.java
Labels: 🔄️refactoring, 🌟feature

#104 🌟(#63 ) 알림서비스 구현
  src/main/java/com/shinhan/knockknock/controller/CardController.java
  src/main/java/com/shinhan/knockknock/controller/NotificationController.java
  src/main/java/com/shinhan/knockknock/domain/dto/CreateCardIssueRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/ReadCardResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/ReadNotificationResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/CardEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/CardIssueEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/NotificationEntity.java
  src/main/java/com/shinhan/knockknock/repository/NotificationRepository.java
  src/main/java/com/shinhan/knockknock/service/CardIssueService.java
  src/main/java/com/shinhan/knockknock/service/CardIssueServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/CardServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/NotificationService.java
  src/main/java/com/shinhan/knockknock/service/NotificationServiceImpl.java
  src/main/resources/static/Notification.html
  src/test/java/com/shinhan/knockknock/controller/CardControllerTest.java
  src/test/java/com/shinhan/knockknock/service/CardIssueServiceImplTest.java
Labels: 🌟feature

#106 🌟(#96 ) 회원 정보 수정 및 탈퇴 구현
  src/main/java/com/shinhan/knockknock/config/SecurityConfig.java
  src/main/java/com/shinhan/knockknock/controller/MatchController.java
  src/main/java/com/shinhan/knockknock/controller/UserController.java
  src/main/java/com/shinhan/knockknock/domain/dto/ReadUserResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/SimpleLoginUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/UpdateUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/UserValidationRequest.java
  src/main/java/com/shinhan/knockknock/domain/entity/MatchEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/UserEntity.java
  src/main/java/com/shinhan/knockknock/repository/MatchRepository.java
  src/main/java/com/shinhan/knockknock/service/MatchService.java
  src/main/java/com/shinhan/knockknock/service/MatchServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/UserService.java
  src/main/java/com/shinhan/knockknock/service/UserServiceImpl.java
  src/test/java/com/shinhan/knockknock/controller/AuthControllerTest.java
  src/test/java/com/shinhan/knockknock/controller/MatchControllerTest.java
  src/test/java/com/shinhan/knockknock/controller/UserControllerTest.java
  src/test/java/com/shinhan/knockknock/service/UserServiceTest.java
Labels: 🌟feature

#113 🌟 CORS 설정 추가
  src/main/java/com/shinhan/knockknock/config/WebConfig.java
Labels: 🌟feature

#118 🌟WebConfig 수정
  src/main/java/com/shinhan/knockknock/config/WebConfig.java
Labels: 🔄️refactoring

#115 🌟(#96 ) 회원 entity date 타입 변경
  src/main/java/com/shinhan/knockknock/domain/dto/UpdateUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/entity/UserEntity.java
Labels: 🔄️refactoring

#125 🌟(#96 ) 회원 기능 수정
  src/main/java/com/shinhan/knockknock/auth/CustomUserDetails.java
  src/main/java/com/shinhan/knockknock/auth/JwtAuthenticationFilter.java
  src/main/java/com/shinhan/knockknock/auth/JwtProvider.java
  src/main/java/com/shinhan/knockknock/config/SecurityConfig.java
  src/main/java/com/shinhan/knockknock/controller/AuthController.java
  src/main/java/com/shinhan/knockknock/controller/MatchController.java
  src/main/java/com/shinhan/knockknock/controller/UserController.java
  src/main/java/com/shinhan/knockknock/domain/dto/match/CreateMatchRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/match/CreateMatchResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/match/DeleteMatchResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/match/UpdateMatchRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/user/CreateUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/user/IdLoginUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/user/LoginUserResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/user/ReadUserResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/user/SimpleLoginUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/user/TokenResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/user/UpdateUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/user/UserValidationRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/user/UserValidationResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/MatchEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/UserEntity.java
  src/main/java/com/shinhan/knockknock/exception/GlobalExceptionHandler.java
  src/main/java/com/shinhan/knockknock/exception/MissingTokenException.java
  src/main/java/com/shinhan/knockknock/service/UserService.java
  src/main/java/com/shinhan/knockknock/service/match/MatchService.java
  src/main/java/com/shinhan/knockknock/service/match/MatchServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/user/AuthService.java
  src/main/java/com/shinhan/knockknock/service/user/UserService.java
  src/main/java/com/shinhan/knockknock/service/user/UserServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/shinhan/knockknock/controller/AuthControllerTest.java
  src/test/java/com/shinhan/knockknock/controller/MatchControllerTest.java
  src/test/java/com/shinhan/knockknock/controller/UserControllerTest.java
  src/test/java/com/shinhan/knockknock/service/UserServiceTest.java
Labels: 🔄️refactoring

#126 🌟(#119 ) 테스트 코드 작성
  src/main/java/com/shinhan/knockknock/domain/dto/CreateCardIssueRequest.java
  src/main/java/com/shinhan/knockknock/domain/entity/CardIssueEntity.java
  src/main/java/com/shinhan/knockknock/domain/entity/RiskEnum.java
  src/main/java/com/shinhan/knockknock/service/CardIssueService.java
  src/main/java/com/shinhan/knockknock/service/CardServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/NotificationServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/test/java/com/shinhan/knockknock/controller/CardControllerTest.java
  src/test/java/com/shinhan/knockknock/repository/CardIssueRepositoryTest.java
  src/test/java/com/shinhan/knockknock/repository/CardRepositoryTest.java
  src/test/java/com/shinhan/knockknock/service/CardIssueServiceImplTest.java
  src/test/java/com/shinhan/knockknock/service/CardServiceImplTest.java
  src/test/java/com/shinhan/knockknock/service/NotificationTest.java
Labels: 💯test

#127 🌟(#56 ) 말동무 돌봄서비스 예약 조회 기능 추가
  src/main/java/com/shinhan/knockknock/controller/ConversationController.java
  src/main/java/com/shinhan/knockknock/controller/ConversationLogController.java
  src/main/java/com/shinhan/knockknock/controller/ConversationRoomController.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversationroom/ConversationRequest.java
  src/main/java/com/shinhan/knockknock/repository/WelfareBookRepository.java
  src/main/java/com/shinhan/knockknock/service/conversation/ConversationService.java
  src/main/java/com/shinhan/knockknock/service/conversation/TextResponseService.java
  src/main/java/com/shinhan/knockknock/service/user/UserServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookService.java
  src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookServiceImpl.java
  src/main/resources/prompts/classification.prompt
  src/test/java/com/shinhan/knockknock/service/WelfareBookServiceTest.java
Labels: 🔄️refactoring, 💯test, 🌟feature

#132 🌟(#56 ) 말동무 예약 내역 조회 기능 추가 및 예외처리
  build.gradle
  src/main/java/com/shinhan/knockknock/controller/ConversationController.java
  src/main/java/com/shinhan/knockknock/controller/ConversationLogController.java
  src/main/java/com/shinhan/knockknock/controller/ConversationRoomController.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/ChatbotResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/ClassificationResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/ConversationLogRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/ConversationLogResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/ConversationRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/ConversationResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/ConversationRoomCreateResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/ConversationRoomResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/ConversationRoomUpdateRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/MessageResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/RedirectionResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/ReservationResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/WelfareBookInfoDto.java
  src/main/java/com/shinhan/knockknock/domain/dto/welfarebook/CreateWelfareBookRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/welfarebook/ReadWelfareBookResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/WelfareBookEntity.java
  src/main/java/com/shinhan/knockknock/repository/WelfareBookRepository.java
  src/main/java/com/shinhan/knockknock/service/conversation/ChainService.java
  src/main/java/com/shinhan/knockknock/service/conversation/ChatbotService.java
  src/main/java/com/shinhan/knockknock/service/conversation/ConversationLogService.java
  src/main/java/com/shinhan/knockknock/service/conversation/ConversationLogServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/conversation/ConversationRoomService.java
  src/main/java/com/shinhan/knockknock/service/conversation/ConversationRoomServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/conversation/ConversationService.java
  src/main/java/com/shinhan/knockknock/service/conversation/PromptService.java
  src/main/java/com/shinhan/knockknock/service/conversation/TextResponseService.java
  src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookService.java
  src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/prompts/basic.prompt
  src/main/resources/prompts/reservation_info.prompt
  src/main/resources/prompts/welfare.prompt
  src/test/java/com/shinhan/knockknock/service/ConversationLogTest.java
  src/test/java/com/shinhan/knockknock/service/ConversationRoomTest.java
  src/test/java/com/shinhan/knockknock/service/WelfareBookServiceTest.java
  src/test/resources/application-test.properties
Labels: 🔄️refactoring, 🌟feature

#133 🌟(#103 ) 복지예약 코드 수정
  src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
  src/main/java/com/shinhan/knockknock/domain/dto/cardhistory/CreateCardHistoryRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/cardhistory/ReadCardHistoryResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/welfarebook/CreateWelfareBookRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/welfarebook/ReadWelfareBookResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/CardHistoryEntity.java
  src/main/java/com/shinhan/knockknock/repository/CardHistoryRepository.java
  src/main/java/com/shinhan/knockknock/repository/WelfareBookRepository.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryService.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookService.java
  src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookServiceImpl.java
Labels: 🔄️refactoring

#134 🌟(#131 ) 소비리포트 구현
  src/main/java/com/shinhan/knockknock/controller/CardController.java
  src/main/java/com/shinhan/knockknock/controller/ConsumptionController.java
  src/main/java/com/shinhan/knockknock/controller/NotificationController.java
  src/main/java/com/shinhan/knockknock/domain/dto/card/CreateCardIssueRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/card/CreateCardIssueResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/card/ReadCardResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/consumption/ReadConsumptionRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/consumption/ReadConsumptionResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/notification/ReadNotificationResponse.java
  src/main/java/com/shinhan/knockknock/repository/CardRepository.java
  src/main/java/com/shinhan/knockknock/repository/ConsumptionRepository.java
  src/main/java/com/shinhan/knockknock/repository/NotificationRepository.java
  src/main/java/com/shinhan/knockknock/service/card/CardIssueService.java
  src/main/java/com/shinhan/knockknock/service/card/CardIssueServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/card/CardService.java
  src/main/java/com/shinhan/knockknock/service/card/CardServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/card/ClovaOCRService.java
  src/main/java/com/shinhan/knockknock/service/consumption/ConsumptionService.java
  src/main/java/com/shinhan/knockknock/service/consumption/ConsumptionServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/notification/NotificationService.java
  src/main/java/com/shinhan/knockknock/service/notification/NotificationServiceImpl.java
  src/main/resources/data.sql
  src/test/java/com/shinhan/knockknock/controller/CardControllerTest.java
  src/test/java/com/shinhan/knockknock/service/CardIssueServiceImplTest.java
  src/test/java/com/shinhan/knockknock/service/CardServiceImplTest.java
  src/test/java/com/shinhan/knockknock/service/NotificationServiceImplTest.java
Labels: 🌟feature

#135 🌟(#56 ) 말동무 response에 바로가기, 예약 정보 추가
  src/main/java/com/shinhan/knockknock/config/SwaggerConfig.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/ChatbotResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/ConversationResponse.java
  src/main/java/com/shinhan/knockknock/service/conversation/ChainService.java
  src/main/java/com/shinhan/knockknock/service/conversation/ChatbotService.java
  src/main/java/com/shinhan/knockknock/service/conversation/ConversationService.java
  src/main/java/com/shinhan/knockknock/service/conversation/PromptService.java
  src/main/java/com/shinhan/knockknock/service/conversation/TextResponseService.java
  src/main/resources/application.properties
  src/main/resources/prompts/basic.prompt
Labels: 🌟feature

#136 🌟(#124) 로그아웃 테스트
  src/main/java/com/shinhan/knockknock/domain/dto/match/CreateMatchResponse.java
  src/main/java/com/shinhan/knockknock/service/match/MatchService.java
  src/main/java/com/shinhan/knockknock/service/user/UserService.java
  src/test/java/com/shinhan/knockknock/controller/AuthControllerTest.java
  src/test/java/com/shinhan/knockknock/controller/MatchControllerTest.java
  src/test/java/com/shinhan/knockknock/service/UserServiceTest.java
Labels: 💯test

#141 🌟(#139 ) 생체 로그인 구현
  src/main/java/com/shinhan/knockknock/controller/AuthController.java
  src/main/java/com/shinhan/knockknock/controller/UserController.java
  src/main/java/com/shinhan/knockknock/domain/dto/user/BioLoginUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/user/CreateUserRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/user/CreateUserResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/user/TokenResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/UserEntity.java
  src/main/java/com/shinhan/knockknock/repository/UserRepository.java
  src/main/java/com/shinhan/knockknock/service/user/AuthService.java
  src/main/java/com/shinhan/knockknock/service/user/UserService.java
  src/main/java/com/shinhan/knockknock/service/user/UserServiceImpl.java
  src/test/java/com/shinhan/knockknock/controller/UserControllerTest.java
Labels: 🌟feature

#146 🌟(#145 ) main.yml 수정
  .github/workflows/main.yml
Labels: 🌏deploy

#148 테이블 이름 수정
  src/main/java/com/shinhan/knockknock/domain/entity/CardIssueEntity.java
Labels: 🐞bugfix

#150 🌟(#146) main.yml 수정
  .github/workflows/main.yml
Labels: 🌏deploy

#155 🌟(#144 ) 말동무 Task 파일 분리 및 예외처리
  src/main/java/com/shinhan/knockknock/controller/ConversationRoomController.java
  src/main/java/com/shinhan/knockknock/repository/CardRepository.java
  src/main/java/com/shinhan/knockknock/repository/ConversationRoomRepository.java
  src/main/java/com/shinhan/knockknock/service/consumption/ConsumptionService.java
  src/main/java/com/shinhan/knockknock/service/consumption/ConsumptionServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/conversation/ConversationRoomServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/conversation/ConversationService.java
  src/main/java/com/shinhan/knockknock/service/conversation/TextResponseService.java
  src/main/java/com/shinhan/knockknock/service/conversation/TokenService.java
  src/main/java/com/shinhan/knockknock/service/conversation/task/ClassificationTaskService.java
  src/main/java/com/shinhan/knockknock/service/conversation/task/DailyConversationTaskService.java
  src/main/java/com/shinhan/knockknock/service/conversation/task/FinanceTaskService.java
  src/main/java/com/shinhan/knockknock/service/conversation/task/GreetingTaskService.java
  src/main/java/com/shinhan/knockknock/service/conversation/task/WelfareTaskService.java
  src/main/resources/prompts/basic.prompt
  src/main/resources/prompts/classification.prompt
  src/main/resources/prompts/finance.prompt
  src/main/resources/prompts/small_talk.prompt
  src/main/resources/prompts/welfare.prompt
  src/test/java/com/shinhan/knockknock/service/ConversationLogTest.java
  src/test/java/com/shinhan/knockknock/service/ConversationRoomTest.java
  src/test/java/com/shinhan/knockknock/service/WelfareBookServiceTest.java
  src/test/java/com/shinhan/knockknock/service/WelfareServiceTest.java
Labels: 🌟feature

#156 🌟(#47 ) 매칭 조회 및 응답 수정
  src/main/java/com/shinhan/knockknock/domain/dto/match/CreateMatchResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/match/UpdateMatchRequest.java
  src/main/java/com/shinhan/knockknock/service/match/MatchService.java
  src/main/java/com/shinhan/knockknock/service/match/MatchServiceImpl.java
  src/test/java/com/shinhan/knockknock/controller/MatchControllerTest.java
Labels: 🔄️refactoring

#160 🌟(#103 ) 카드내역, 복지예약 코드 수정
  src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
  src/main/java/com/shinhan/knockknock/domain/dto/cardhistory/ReadCardHistoryResponse.java
  src/main/java/com/shinhan/knockknock/repository/CardHistoryRepository.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryService.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
Labels: 🔄️refactoring, 🌟feature

#162 🌟(#103 ) swagger https 주소변경
  src/main/java/com/shinhan/knockknock/config/SwaggerConfig.java
  src/main/java/com/shinhan/knockknock/repository/CardHistoryRepository.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
Labels: 🔄️refactoring

#164 🌟(#103 ) swagger https 주소변경
  src/main/java/com/shinhan/knockknock/config/SwaggerConfig.java
Labels: 🔄️refactoring

#166 🌟(#159 ) 카드 로직 수정, 알림 기능 추가
  src/main/java/com/shinhan/knockknock/controller/CardController.java
  src/main/java/com/shinhan/knockknock/controller/NotificationController.java
  src/main/java/com/shinhan/knockknock/domain/dto/card/ReadCardResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/card/ReadCardSingleResponse.java
  src/main/java/com/shinhan/knockknock/repository/NotificationRepository.java
  src/main/java/com/shinhan/knockknock/service/card/CardService.java
  src/main/java/com/shinhan/knockknock/service/card/CardServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/notification/NotificationService.java
  src/main/java/com/shinhan/knockknock/service/notification/NotificationServiceImpl.java
  src/main/resources/data.sql
Labels: 🌟feature

#168 🌟(#144 ) 소비 리포트 읽어주기 기능 추가
  src/main/java/com/shinhan/knockknock/controller/ConversationController.java
  src/main/java/com/shinhan/knockknock/domain/dto/conversation/ConsumptionResponse.java
  src/main/java/com/shinhan/knockknock/repository/CardHistoryRepository.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryService.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/consumption/ConsumptionService.java
  src/main/java/com/shinhan/knockknock/service/consumption/ConsumptionServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/conversation/ChainService.java
  src/main/java/com/shinhan/knockknock/service/conversation/PromptService.java
  src/main/java/com/shinhan/knockknock/service/conversation/TokenService.java
  src/main/java/com/shinhan/knockknock/service/conversation/task/FinanceTaskService.java
  src/main/resources/prompts/consumption_report.prompt
  src/main/resources/prompts/finance.prompt
  src/main/resources/static/conversation.html
Labels: 🌟feature

#169 🌟(#103) 복지예약 수정중
  src/main/java/com/shinhan/knockknock/controller/WelfareBookController.java
  src/main/java/com/shinhan/knockknock/domain/dto/welfarebook/CreateWelfareBookRequest.java
  src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookService.java
  src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookServiceImpl.java
Labels: 🔄️refactoring

#171 🌟(#167 ) 회원 정보 조회
  src/main/java/com/shinhan/knockknock/controller/CardController.java
  src/main/java/com/shinhan/knockknock/domain/dto/card/ReadMemberInfo.java
  src/main/java/com/shinhan/knockknock/repository/UserRepository.java
  src/main/java/com/shinhan/knockknock/service/card/CardIssueService.java
  src/main/java/com/shinhan/knockknock/service/card/CardIssueServiceImpl.java
Labels: 🌟feature

#173 🌟(#167) 스케줄러 구현 및 카드 조회 수정
  src/main/java/com/shinhan/knockknock/BackendApplication.java
  src/main/java/com/shinhan/knockknock/config/SchedulerConfig.java
  src/main/java/com/shinhan/knockknock/repository/CardRepository.java
  src/main/java/com/shinhan/knockknock/repository/MatchRepository.java
  src/main/java/com/shinhan/knockknock/service/card/CardServiceImpl.java
Labels: 🌟feature

#179 🌟sql문 추가
  src/main/java/com/shinhan/knockknock/config/CustomSqlLoader.java
  src/main/resources/application.properties
  src/main/resources/sql/cardcategory.sql
  src/main/resources/sql/cardhistory.sql
Labels: 🌟feature

#182 🌟testEntity 삭제
  src/main/java/com/shinhan/knockknock/domain/entity/TestEntity.java
Labels: 🔄️refactoring

#184 🌟(#175) 카드내역 detail조회 추가
  src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryService.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
Labels: 🌟feature
