Repository Knock-and-knock/backend, pull requests merged in 2024-09, with the labels that each got.

#186 🌟조회항목 추가
  src/main/java/com/shinhan/knockknock/domain/dto/cardhistory/ReadCardHistoryResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/welfarebook/ReadWelfareBookResponse.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookService.java
Labels: 🔄️refactoring

#189 🌟swagger local path 추가
  src/main/java/com/shinhan/knockknock/config/SwaggerConfig.java
  src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryService.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
Labels: 🌟feature

#190 [Feat]: 로그 추가
  src/main/java/com/shinhan/knockknock/config/WebConfig.java
  src/main/java/com/shinhan/knockknock/interceptor/ApiLoggingInterceptor.java
Labels: 🌟feature

#191 🌟cardhistory detail조회 수정
  src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryService.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
Labels: 🔄️refactoring

#196 🌟복지 예약, 복지 리스트 코드 수정
  src/main/java/com/shinhan/knockknock/controller/WelfareBookController.java
  src/main/java/com/shinhan/knockknock/domain/dto/cardhistory/DetailCardHistoryResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/welfare/ReadWelfareResponse.java
  src/main/java/com/shinhan/knockknock/domain/dto/welfarebook/CreateWelfareBookRequest.java
  src/main/java/com/shinhan/knockknock/repository/CardCategoryRepository.java
  src/main/java/com/shinhan/knockknock/repository/CardHistoryRepository.java
  src/main/java/com/shinhan/knockknock/repository/CardRepository.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/welfare/WelfareService.java
  src/main/resources/sql/user.sql
Labels: 🔄️refactoring, 🌟feature

#201 Bugfix card family
  src/main/java/com/shinhan/knockknock/domain/dto/card/CreateCardIssueRequest.java
Labels: 🔄️refactoring

#203 🌟카드내역 정렬
  src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
  src/main/java/com/shinhan/knockknock/repository/CardHistoryRepository.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/welfarebook/WelfareBookServiceImpl.java
Labels: 🔄️refactoring

#202 🌟(#95 ) 회원 데이터 수정
  src/main/resources/sql/user.sql
Labels: 🔄️refactoring

#204 🌟(#200 ) sql문
  src/main/java/com/shinhan/knockknock/config/CustomSqlLoader.java
  src/main/java/com/shinhan/knockknock/repository/CardIssueRepository.java
  src/main/java/com/shinhan/knockknock/service/card/CardIssueServiceImpl.java
  src/main/resources/sql/card.sql
  src/main/resources/sql/cardhistory.sql
  src/main/resources/sql/cardissue.sql
  src/main/resources/sql/user.sql
Labels: 🔄️refactoring

#206 🌟이상징후 알림 스케쥴러 임시, 복지예약 데이터 추가
  src/main/java/com/shinhan/knockknock/config/cardHistorySchedulerConfig.java
  src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
  src/main/resources/sql/welfarebook.sql
Labels: 🌟feature

#207 🌟sql문 수정
  src/main/java/com/shinhan/knockknock/config/CustomSqlLoader.java
Labels: 🔄️refactoring

#208 매칭 데이터 추가
  src/main/java/com/shinhan/knockknock/config/CustomSqlLoader.java
  src/main/java/com/shinhan/knockknock/controller/UserController.java
  src/main/java/com/shinhan/knockknock/service/match/MatchServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/user/UserServiceImpl.java
  src/main/resources/sql/match.sql
Labels: 🌟feature

#209 🌟(#200 ) sql
  src/main/resources/sql/cardissue.sql
Labels: 🌟feature

#212 🌟로그 추가
  src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
Labels: 🔄️refactoring

#214 🌟로그 추가
  src/main/java/com/shinhan/knockknock/controller/CardHistoryController.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
Labels: 🔄️refactoring

#211 🌟(#200 ) 전화번호 형식 수정, issue sql, 검증코드
  src/main/java/com/shinhan/knockknock/domain/dto/card/CreateCardIssueRequest.java
  src/main/java/com/shinhan/knockknock/domain/entity/RiskEnum.java
  src/main/java/com/shinhan/knockknock/service/card/CardIssueServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/card/CardServiceImpl.java
  src/main/resources/sql/cardissue.sql
Labels: 🌟feature

#218 ## 🌟(#200 ) 코드 수정
  src/main/java/com/shinhan/knockknock/service/card/CardIssueServiceImpl.java
Labels: 🐞bugfix

#219 🌟(#200 ) 수정
  src/main/java/com/shinhan/knockknock/domain/dto/card/ReadCardIssueResponse.java
  src/main/java/com/shinhan/knockknock/service/card/CardIssueService.java
Labels: 🐞bugfix

#221 🌟welfarebook sql 쿼리추가
  src/main/resources/sql/welfarebook.sql
Labels: 🔄️refactoring

#223 [bugfix] 카드 발급, 소비리포트
  src/main/java/com/shinhan/knockknock/config/SchedulerConfig.java
  src/main/java/com/shinhan/knockknock/controller/CardController.java
  src/main/java/com/shinhan/knockknock/repository/CardHistoryRepository.java
  src/main/java/com/shinhan/knockknock/service/card/CardIssueServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/card/CardServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/consumption/ConsumptionServiceImpl.java
  src/main/java/com/shinhan/knockknock/service/notification/NotificationServiceImpl.java
Labels: 🐞bugfix

#227 🌟프론트 cardHistory data넣는 페이지 제작
  src/main/java/com/shinhan/knockknock/config/SecurityConfig.java
  src/main/java/com/shinhan/knockknock/controller/CardHistoryDataController.java
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
  src/main/resources/static/card-history.html
  src/main/resources/static/login.html
Labels: 🌟feature

#226 🌟(#224 ) 간편결제 비밀번호 구현
  src/main/java/com/shinhan/knockknock/auth/JwtAuthenticationFilter.java
  src/main/java/com/shinhan/knockknock/controller/AuthController.java
  src/main/java/com/shinhan/knockknock/controller/UserController.java
  src/main/java/com/shinhan/knockknock/domain/dto/user/SimplePaymentRequest.java
  src/main/java/com/shinhan/knockknock/domain/dto/user/SimplePaymentResponse.java
  src/main/java/com/shinhan/knockknock/domain/entity/UserEntity.java
  src/main/java/com/shinhan/knockknock/service/user/UserService.java
  src/main/java/com/shinhan/knockknock/service/user/UserServiceImpl.java
Labels: 🌟feature

#231 🌟(#144 ) 말동무 바로가기 수정
  src/main/java/com/shinhan/knockknock/service/conversation/task/WelfareTaskService.java
Labels: 🐞bugfix

#239 🌟(#95 ) 전화번호 중복 체크 삭제
  src/main/java/com/shinhan/knockknock/auth/JwtProvider.java
  src/main/java/com/shinhan/knockknock/controller/UserController.java
  src/main/java/com/shinhan/knockknock/service/user/UserServiceImpl.java
Labels: 🔄️refactoring

#242 🌟(#124 ) 로그아웃 및 필터 예외처리
  src/main/java/com/shinhan/knockknock/auth/JwtAuthenticationFilter.java
  src/main/java/com/shinhan/knockknock/auth/JwtProvider.java
  src/main/java/com/shinhan/knockknock/controller/AuthController.java
  src/main/java/com/shinhan/knockknock/service/user/AuthService.java
Labels: 🔄️refactoring

#248 🌟숫자 단위 , 추가
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
Labels: 🔄️refactoring

#247 🌟(#96 ) 정보수정 주소 null 처리
  src/main/java/com/shinhan/knockknock/service/user/UserServiceImpl.java
Labels: 🔄️refactoring

#249 🌟알림 카테고리 이름 변경
  src/main/java/com/shinhan/knockknock/service/cardhistory/CardHistoryServiceImpl.java
Labels: 🔄️refactoring

#250 🌟(#241) 일부 수정
  src/main/java/com/shinhan/knockknock/service/card/CardServiceImpl.java
  src/main/resources/sql/card.sql
Labels: 🛠️fix
